### ISSUE TITLE
Terminology description

### ISSUE THREAD

**Issue by JunqiZhang0** [abraverm/openengine#7]
We should have a documentation for developer:
**something like:**

-------------------
```yaml
---
Server:
  implicit:
    _memory:
      type: string
    _disk:
      type: string
  providers:
    - action: create
      match:
        type: object
        properties:
          providerType:
            type: string
      parameters:
        imageRef:
          required: true
          explicit:
            type: string
```
-------------------
**DSL.API:**
  description: This is the place where stores the path of the **api** in bdsl.yaml
  example:
    _api:
      - provider.yaml_
**ProviderAPI:** (type ProviderAPI map[string]ProviderAPIResources)
  description:
    **below is how ProviderAPI is filled with information**
    data, err := getSource(provider:TYPE(DSL.API)) //data is the variable containing all provider information from bdsl.yml
    yaml.UnmarshalWithOptions(data, &parsedData:TYPE(engine.ProviderAPI), yaml.Strict())
    e.AddProvider(parsedData)

**ProviderAPIResources:** 
  description:
    It has two fields, Implcit:TYPE(map[string]Schema)  , Providers :TYPE([]Provider). This is exactly where the information from 
    provider.yml (inside bdsl.yml) will go via the deserialization
